const $=q=>document.querySelector(q);let lang=localStorage.kirLang||"uk",S={},timer,storyTimers=[];
const copy={uk:{intro:["ПЕРШИЙ ДЕНЬ","Тобі сказали просто сидіти тут дві хвилини й нічого не чіпати. Звучить підозріло просто."],lamp:["ЗАГОРІЛАСЯ ЖОВТА","Хвилину тому вона точно не горіла. Хоча ти тут перший день, тому хуй його знає."],hum:["ЩОСЬ ЗАГУЛО","Гул іде десь знизу. Або зверху. Коротше, установка почала проявляти характер."],call:["ТЕЛЕФОН ДЗВОНИТЬ","Він дзвонить уже непристойно довго. Можливо, на тому кінці знають, що означає жовта лампочка."],red:["НУ НАХУЯ?","Там буквально було написано «НЕ НАТИСКАТИ». Тепер десь у будівлі щось дуже солідно клацнуло."],hz:["РУБИЛЬНИК «ХЗ»","Ти його смикнув. На секунду згасло світло в туалеті. Схоже, установка цього навіть не помітила."],vasya:["Я ж написав №1 не чіпати.","...Хоча стоп. Це записка ще з минулого пульта.","Якщо червона не блимає — значить усе нормально. Напевно."],phone:["Начальник питає, чи все нормально. Ти подивився на пульт і впевнено сказав: «Так».","Диспетчер попросив назвати показники. Ти сказав: «В межах норми». Якої саме — не уточнив.","У трубці Вася: «Я там записку лишив». Дуже корисна інформація."]},
en:{intro:["FIRST DAY","They told you to sit here for two minutes and touch nothing. Suspiciously simple."],lamp:["THE YELLOW LIGHT IS ON","It definitely wasn't on a minute ago. Then again, it's your first day, so who knows."],hum:["SOMETHING IS HUMMING","The hum comes from below. Or above. Anyway, the plant has developed a personality."],call:["THE PHONE IS RINGING","It's been ringing for an indecent amount of time. Maybe whoever's calling knows what the yellow light means."],red:["WHY WOULD YOU DO THAT?","It literally said DO NOT PRESS. Something very substantial just clicked somewhere in the building."],hz:["THE ??? SWITCH","You pulled it. The restroom lights went out for a second. The plant seems unimpressed."],vasya:["I wrote not to touch #1.","...Wait. That note is from the old panel.","If the red one isn't flashing, everything's fine. Probably."],phone:["Boss asks if everything is fine. You looked at the panel and confidently said: “Yes.”","Dispatcher asked for readings. You said: “within limits.” Which limits, you didn't specify.","Vasya: “I left you a note.” Extremely useful information."]}};
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}
function tone(f=400,d=.07){try{let a=window._a||(window._a=new (AudioContext||webkitAudioContext)()),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch{}}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function story(k){let c=copy[lang][k];$("#storyTitle").textContent=c[0];$("#storyText").textContent=c[1];$("#story").classList.remove("hidden")}
function vasya(text){$("#person").classList.remove("hidden");$("#bubble").classList.remove("hidden");$("#speech").textContent=text;setTimeout(()=>$("#bubble").classList.add("hidden"),4200);setTimeout(()=>$("#person").classList.add("hidden"),6500)}
function later(sec,fn){storyTimers.push(setTimeout(fn,sec*1000))}
function start(){storyTimers.forEach(clearTimeout);clearInterval(timer);S={start:Date.now(),duration:120,toggle:false,knob:2,phone:false,reds:0,weird:0,calls:0,ended:false};show("#game");$("#yellow").classList.remove("on");$("#alarmLamp").classList.remove("on");$("#story").classList.add("hidden");$("#person").classList.add("hidden");$("#bubble").classList.add("hidden");render();story("intro");
later(13,()=>{story("lamp");$("#yellow").classList.add("on");tone(610,.1)});
later(29,()=>{story("hum");tone(170,.15)});
later(43,()=>vasya(copy[lang].vasya[0]));
later(58,()=>{S.phone=true;story("call");render();ring()});
later(80,()=>vasya(copy[lang].vasya[1]));
later(101,()=>vasya(copy[lang].vasya[2]));
timer=setInterval(()=>{let left=Math.max(0,S.duration-(Date.now()-S.start)/1000);$("#clock").textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(Math.floor(left%60)).padStart(2,"0")}`;if(left<=0)finish()},250)}
function render(){$("#toggle").classList.toggle("on",S.toggle);$("#toggleState").textContent=S.toggle?(lang==="uk"?"УВІМК":"ON"):(lang==="uk"?"ВИМК":"OFF");$("#knobState").textContent=S.knob;$("#knob").style.transform=`rotate(${-70+S.knob*35}deg)`;$("#phone").classList.toggle("ring",S.phone);$("#phoneState").textContent=S.phone?(lang==="uk"?"ДЗВОНИТЬ":"RINGING"):(lang==="uk"?"МОВЧИТЬ":"SILENT")}
function ring(){if(!S.phone)return;tone(760,.12);setTimeout(()=>{if(S.phone)tone(760,.12)},450);setTimeout(()=>{if(S.phone)ring()},2500)}
$("#toggle").onclick=()=>{S.toggle=!S.toggle;S.weird++;tone(300);toast(S.toggle?(lang==="uk"?"Десь щось запрацювало. Уже пізно питати що.":"Something started somewhere. Too late to ask what."):(lang==="uk"?"Воно перестало гудіти. Інше почало.":"It stopped humming. Something else started."));render()};
$("#knob").onclick=()=>{S.knob=S.knob%4+1;S.weird++;tone(260+S.knob*70);toast(lang==="uk"?["Менше.","Трошки більше.","Ще більше.","О. Це вже багато."][S.knob-1]:["Less.","A bit more.","More.","Okay. That's a lot."][S.knob-1]);render()};
$("#phone").onclick=()=>{if(S.phone){S.phone=false;S.calls++;tone(430);toast(copy[lang].phone[Math.floor(Math.random()*3)]);render()}else toast(lang==="uk"?"Тиша. Навіть дивно.":"Silence. Weirdly comforting.")};
$("#hz").onclick=()=>{S.weird++;story("hz");tone(120,.2);navigator.vibrate?.([50,30,50])};
$("#red").onclick=()=>{S.reds++;S.weird++;story("red");$("#alarmLamp").classList.add("on");tone(85,.35);navigator.vibrate?.([100,50,160]);setTimeout(()=>$("#alarmLamp").classList.remove("on"),5000)};
function finish(){if(S.ended)return;S.ended=true;clearInterval(timer);storyTimers.forEach(clearTimeout);$("#reds").textContent=S.reds;$("#weird").textContent=S.weird;$("#calls").textContent=S.calls;$("#finalQuote").innerHTML=S.reds? (lang==="uk"?"«Кнопку ж підписали. Нащо?»<br><b>— Вася</b>":"“The button was labeled. Why?”<br><b>— Vasya</b>"):(lang==="uk"?"«Для першого дня — нормально.»<br><b>— Вася</b>":"“For a first day — acceptable.”<br><b>— Vasya</b>");show("#result");navigator.vibrate?.([40,50,90])}
$("#start").onclick=start;$("#again").onclick=start;$("#menuBtn").onclick=()=>show("#menu");$("#lang").onclick=()=>{lang=lang==="uk"?"en":"uk";localStorage.kirLang=lang;toast(lang==="uk"?"Українська":"English")};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=0061").then(r=>r.update()).catch(()=>{});