const $=q=>document.querySelector(q), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let lang=localStorage.kirLang||"uk", state={}, tick, eventTimer, phoneTimer, currentTask=null;
const L={uk:{tag:"Головне — не зробити гірше.",shift:"ЗМІНА 01 // ПЕРШИЙ ДЕНЬ",temp:"ТЕМПЕРАТУРА",press:"КОНТУР",pump:"НАСОС",fan:"ВЕНТИЛЯТОР",valve:"КЛАПАН",alarm:"СИРЕНА",phone:"ТЕЛЕФОН",quiet:"мовчить",ring:"ДЗВОНИТЬ!",on:"УВІМК",off:"ВИМК",ready:"ГОТОВА",muted:"ЗАТКНУТА",task:"ЩОСЬ НЕ ТАК",hint:"Підказка",survive:"ВИ ВИЖИЛИ",surviveSub:"Реактор теж. Дивовижно.",fail:"НУ МАЙЖЕ",failSub:"Комісія просить більше не приходити.",grade:["ГЕНІЙ","ЗАДОВІЛЬНО","ПІДОЗРІЛО","ЯК ТИ СЮДИ ПОТРАПИВ?"],toasts:["Ти натиснув «ХЗ». Сміливо.","Десь згасло світло. Не тут.","Нічого. Це лякає найбільше."],red:["Кнопка була підписана.","Десь дуже далеко щось клацнуло.","Ти ж бачив напис, так?"],call:["Начальник: «Ну як там?» — Ти: «Нормально».","Вася: «Не чіпай червону». Дуже вчасно.","Диспетчер питає показники. Ти сказав: «зелені»."]},
en:{tag:"Main objective: don't make it worse.",shift:"SHIFT 01 // FIRST DAY",temp:"TEMPERATURE",press:"LOOP",pump:"PUMP",fan:"FAN",valve:"VALVE",alarm:"ALARM",phone:"PHONE",quiet:"silent",ring:"RINGING!",on:"ON",off:"OFF",ready:"ARMED",muted:"MUTED",task:"SOMETHING IS WRONG",hint:"Hint",survive:"YOU SURVIVED",surviveSub:"So did the reactor. Amazing.",fail:"ALMOST",failSub:"Management asks you not to return.",grade:["GENIUS","ACCEPTABLE","SUSPICIOUS","HOW DID YOU GET THIS JOB?"],toasts:["You pulled the ??? switch. Bold.","Some lights went out. Not here.","Nothing happened. That's worse."],red:["The button had a label.","Something huge clicked far away.","You did see the warning, right?"],call:["Boss: “How's it going?” — “Fine.”","Vasya: “Don't touch the red one.” Great timing.","Dispatcher asks for readings. You said: “green.”"]}};
const tasks=[
 {id:"hot",at:20,uk:["ЩОСЬ ГАРЯЧЕ","Температура повзе вгору.","Спробуй увімкнути щось, що ганяє повітря."],en:["SOMETHING IS HOT","Temperature is creeping up.","Try switching on something that moves air."],solve:()=>state.fan},
 {id:"pump",at:52,uk:["НАСОС МОВЧИТЬ","Лампочка насоса теж. Підозріло.","Тумблер насоса виглядає достатньо офіційно."],en:["THE PUMP IS SILENT","Its lamp is too. Suspicious.","The pump toggle looks official enough."],solve:()=>state.pump},
 {id:"pressure",at:86,uk:["МАНОМЕТР ЛІЗЕ ВГОРУ","Стрілка явно кудись поспішає.","Може, клапан не повинен стояти посередині?"],en:["PRESSURE IS CLIMBING","The needle is clearly in a hurry.","Maybe the valve shouldn't sit halfway?"],solve:()=>state.valve>=75},
 {id:"phone",at:120,uk:["ХТОСЬ ДЗВОНИТЬ","Телефон не перестане сам.","Можна навіть підняти слухавку."],en:["SOMEONE IS CALLING","The phone won't stop itself.","You could actually answer it."],solve:()=>state.calls>0},
 {id:"combo",at:150,uk:["О, ТЕПЕР ГУДЕ","І температура знову росте.","Насос + вентилятор. Високі технології."],en:["NOW IT'S HUMMING","And temperature is rising again.","Pump + fan. Advanced technology."],solve:()=>state.pump&&state.fan}
];
function tr(x){return x[lang]}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}
function tone(f=350,d=.06){try{let A=window._a||(window._a=new (AudioContext||webkitAudioContext)()),o=A.createOscillator(),g=A.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(A.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,A.currentTime+d);o.stop(A.currentTime+d)}catch{}}
function buzz(p=[25]){navigator.vibrate?.(p)}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1500)}
function setNeedle(id,v){$(id+" .needle").style.transform=`rotate(${-125+clamp(v,0,100)*2.5}deg)`}
function labels(){let l=L[lang];$("#tagline").textContent=l.tag;$("#shiftTitle").textContent=l.shift;$("#tempLabel").textContent=l.temp;$("#pressLabel").textContent=l.press;$("#pumpText").textContent=l.pump;$("#fanText").textContent=l.fan;$("#valveText").textContent=l.valve;$("#alarmText").textContent=l.alarm;$("#phoneTitle").textContent=l.phone;$("#l1name").textContent=lang==="uk"?"ПЕРШИЙ ДЕНЬ":"FIRST DAY";$("#l1sub").textContent=lang==="uk"?"Навіть Вася колись починав.":"Even Vasya had a first day.";$("#l2name").textContent=lang==="uk"?"КОЛЕГА":"COWORKER";$("#l2sub").textContent=lang==="uk"?"Він тут уже двадцять років.":"He's been here twenty years.";$("#l3name").textContent=lang==="uk"?"СЕКРЕТАРКА":"SECRETARY";$("#l3sub").textContent=lang==="uk"?"«Ти каву будеш?»":"“Want coffee?”";$("#l4name").textContent=lang==="uk"?"ПЕРЕВІРКА":"INSPECTION";$("#l4sub").textContent=lang==="uk"?"Роби вигляд, що все нормально.":"Pretend everything is fine.";render()}
function render(){if(!state.started)return;let l=L[lang];$("#pump").classList.toggle("on",state.pump);$("#fan").classList.toggle("on",state.fan);$("#pumpState").textContent=state.pump?l.on:l.off;$("#fanState").textContent=state.fan?l.on:l.off;$("#valveState").textContent=state.valve+"%";$("#valve").style.transform=`rotate(${(state.valve-50)*2.2}deg)`;$("#alarmState").textContent=state.silenced?l.muted:l.ready;$("#phoneState").textContent=state.phone?l.ring:l.quiet;$("#phone").classList.toggle("ring",state.phone);$('[data-lamp="pump"]').classList.toggle("on",state.pump);$('[data-lamp="alarm"]').classList.toggle("on",state.danger&&!state.silenced);$('[data-lamp="unknown"]').classList.toggle("on",Math.random()<.04);setNeedle("#gTemp",state.temp);setNeedle("#gPress",state.pressure);document.body.classList.toggle("danger",state.danger)}
function startGame(){clearInterval(tick);clearInterval(eventTimer);state={started:true,start:Date.now(),duration:180,temp:34,pressure:38,pump:false,fan:false,valve:50,silenced:false,phone:false,calls:0,mistakes:0,reds:0,done:new Set(),alive:true};currentTask=null;show("#game");render();tick=setInterval(step,500);setTimeout(()=>toast(lang==="uk"?"Три хвилини. Не зламай.":"Three minutes. Don't break it."),700)}
function step(){if(!state.alive)return;let elapsed=(Date.now()-state.start)/1000,left=Math.max(0,state.duration-elapsed);$("#clock").textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(Math.floor(left%60)).padStart(2,"0")}`;
state.temp += (.32-(state.fan?.28:0)-(state.pump?.18:0))*.5;
state.pressure += (.13-(state.valve>=75?.16:0)+(state.valve<=25?.16:0))*.5;
for(const t of tasks){if(elapsed>=t.at&&!state.done.has(t.id)&&(!currentTask||currentTask.id!==t.id)){currentTask=t;showTask(t);break}}
if(currentTask&&currentTask.solve()){state.done.add(currentTask.id);toast(lang==="uk"?"О. Допомогло. Не звикай.":"Oh. It worked. Don't get used to it.");$("#task").classList.add("hidden");currentTask=null;state.temp=Math.max(25,state.temp-7);state.pressure=Math.max(25,state.pressure-5);tone(520)}
if(elapsed>112&&!state.phone&&state.calls===0)ringPhone();
state.danger=state.temp>72||state.pressure>78;
if(state.temp>=100||state.pressure>=100){state.alive=false;finish(false)}
if(left<=0)finish(true);render()}
function showTask(t){$("#task").classList.remove("hidden");$("#taskKind").textContent=L[lang].task;$("#taskTitle").textContent=t[lang][0];$("#taskBody").textContent=t[lang][1];$("#taskHint").textContent=L[lang].hint+": "+t[lang][2];tone(700,.12);buzz([70,50,70])}
function ringPhone(){state.phone=true;tone(800,.12);setTimeout(()=>state.phone&&tone(800,.12),500)}
function finish(win){if(!state.alive&&win)return;state.alive=false;clearInterval(tick);show("#result");let l=L[lang];$("#resultTitle").textContent=win?l.survive:l.fail;$("#resultSub").textContent=win?l.surviveSub:l.failSub;$("#mistakes").textContent=state.mistakes;$("#redCount").textContent=state.reds;$("#calls").textContent=state.calls;let bad=state.mistakes+state.reds*2;$("#grade").textContent=l.grade[bad<=1?0:bad<=4?1:bad<=8?2:3];buzz(win?[50,50,100]:[200,80,300])}
$("#pump").onclick=()=>{state.pump=!state.pump;tone();render()};
$("#fan").onclick=()=>{state.fan=!state.fan;tone();render()};
$("#valve").onclick=()=>{state.valve=state.valve>=75?25:state.valve+25;tone(280);render()};
$("#silence").onclick=()=>{state.silenced=!state.silenced;toast(lang==="uk"?"Сирена замовкла. Аварія — ні.":"Alarm silenced. Emergency remains.");state.mistakes++;render()};
$("#phone").onclick=()=>{if(state.phone){state.phone=false;state.calls++;toast(L[lang].call[Math.floor(Math.random()*L[lang].call.length)]);tone(420);render()}else toast(lang==="uk"?"Ти подзвонив сам собі. Зайнято.":"You called yourself. Busy.")};
$("#hz").onclick=()=>{state.mistakes++;state.temp+=Math.random()*12-4;state.pressure+=Math.random()*12-4;toast(L[lang].toasts[Math.floor(Math.random()*3)]);tone(170,.12);render()};
$("#red").onclick=()=>{state.reds++;state.mistakes++;state.temp+=9;state.pressure+=7;toast(L[lang].red[Math.floor(Math.random()*3)]);tone(90,.25);buzz([80,40,100]);render()};
$("#level1").onclick=startGame;$("#again").onclick=startGame;$("#toMenu").onclick=()=>show("#menu");$("#nextLevel").onclick=()=>toast(lang==="uk"?"Рівень 02 буде наступним 😈":"Level 02 is next 😈");$("#pause").onclick=()=>{toast(lang==="uk"?"Перерва? На реакторі? 😂":"A break? At a reactor? 😂")};
$("#lang").onclick=()=>{lang=lang==="uk"?"en":"uk";localStorage.kirLang=lang;labels()};
labels();show("#menu");
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=006").then(r=>r.update()).catch(()=>{});