const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const T={uk:{unit:'БЛОК R-01',survival:'ЧАС РОБОТИ',best:'РЕКОРД',stable:'СТАБІЛЬНО',warning:'УВАГА',critical:'КРИТИЧНО',lost:'БЛОК ВТРАЧЕНО',noAlarms:'НЕМАЄ АКТИВНИХ ТРИВОГ',fault:'НЕСПРАВНІСТЬ',meters:{temp:'ТЕМП. ЯДРА',pressure:'ТИСК',power:'ПОТУЖНІСТЬ',coolant:'ТЕПЛОНОСІЙ',stability:'СТАБІЛЬНІСТЬ'},controls:{pump:'НАСОС ОХОЛОДЖЕННЯ',generator:'ДОП. ГЕНЕРАТОР',valve:'ГОЛОВНИЙ КЛАПАН',vent:'СКИДАННЯ ТИСКУ',cool:'АВАР. ОХОЛОДЖЕННЯ'},on:'УВІМК',off:'ВИМК',open:'ВІДКРИТО',closed:'ЗАКРИТО',charges:'ЗАРЯДИ',ready:'ГОТОВИЙ',fired:'СПРАЦЮВАВ',logLabel:'ЖУРНАЛ ПОДІЙ',restart:'ПЕРЕЗАПУСТИТИ БЛОК',footer:'R-01 // ТЕРМІНАЛ КЕРУВАННЯ v0.04',online:'R-01 у мережі. Перші секунди — стабільний режим.',valveLog:'Головний клапан',coolLog:'Аварійне охолодження активовано.',scramLog:'SCRAM активовано. Реактор глушиться.',alarms:['ВИСОКА ТЕМПЕРАТУРА ЯДРА','ВИСОКИЙ ТИСК','НИЗЬКА ПОТУЖНІСТЬ МЕРЕЖІ','НИЗЬКИЙ РІВЕНЬ ТЕПЛОНОСІЯ','СИСТЕМА НЕСТАБІЛЬНА'],death:['ПЕРЕГРІВ ЯДРА. Блок втрачено.','РУЙНУВАННЯ КОРПУСУ ВІД ТИСКУ.','ТЕПЛОНОСІЙ ВИЧЕРПАНО.','КАСКАДНА ВТРАТА СТАБІЛЬНОСТІ.'],faults:{pump:'ЗБІЙ НАСОСА: ефективність охолодження знижена.',leak:'ВИТІК ТЕПЛОНОСІЯ: рівень падає.',grid:'СТРИБОК НАВАНТАЖЕННЯ: мережа просідає.',valve:'КЛАПАН ЗАКЛИНИЛО: тиск росте.',sensor:'ЗБІЙ КОНТУРУ: система втрачає стабільність.'}},
en:{unit:'UNIT R-01',survival:'SURVIVAL',best:'BEST',stable:'STABLE',warning:'WARNING',critical:'CRITICAL',lost:'UNIT LOST',noAlarms:'NO ACTIVE ALARMS',fault:'FAULT',meters:{temp:'CORE TEMP',pressure:'PRESSURE',power:'POWER',coolant:'COOLANT',stability:'STABILITY'},controls:{pump:'COOLANT PUMP',generator:'AUX GENERATOR',valve:'MAIN VALVE',vent:'PRESSURE VENT',cool:'EMERG. COOLING'},on:'ON',off:'OFF',open:'OPEN',closed:'CLOSED',charges:'CHARGES',ready:'ARMED',fired:'TRIPPED',logLabel:'EVENT LOG',restart:'RESTART UNIT',footer:'R-01 // CONTROL TERMINAL v0.04',online:'R-01 online. Initial conditions stable.',valveLog:'Main valve',coolLog:'Emergency cooling activated.',scramLog:'SCRAM activated. Reactor shutdown in progress.',alarms:['HIGH CORE TEMPERATURE','HIGH PRESSURE','LOW GRID POWER','LOW COOLANT LEVEL','SYSTEM UNSTABLE'],death:['CORE OVERHEAT. Unit lost.','PRESSURE VESSEL FAILURE.','COOLANT DEPLETED.','CASCADE STABILITY LOSS.'],faults:{pump:'PUMP FAILURE: cooling efficiency reduced.',leak:'COOLANT LEAK: inventory falling.',grid:'LOAD SURGE: grid power collapsing.',valve:'VALVE JAM: pressure rising.',sensor:'CONTROL LOOP FAULT: stability falling.'}}};
let lang=localStorage.kirLang||'uk',s,alive,last,started,best=Number(localStorage.kirBest||0),coolCharges,fault=null,nextFault=18,audioCtx;
const keys=['temp','pressure','power','coolant','stability'];
const meters=document.querySelector('#meters');
function buzz(pattern=[60]){if(navigator.vibrate)navigator.vibrate(pattern)}
function beep(freq=440,dur=.08){try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch(e){}}
function buildMeters(){meters.innerHTML='';keys.forEach(k=>meters.insertAdjacentHTML('beforeend',`<div class="meter"><span>${T[lang].meters[k]}</span><div class="track"><div id="bar-${k}" class="fill"></div></div><span id="v-${k}" class="value"></span></div>`))}
function applyLanguage(){document.documentElement.lang=lang;unitLabel.textContent=T[lang].unit;survivalLabel.textContent=T[lang].survival;logLabel.textContent=T[lang].logLabel;restart.textContent=T[lang].restart;footer.textContent=T[lang].footer;document.querySelector('#lang-uk').classList.toggle('active',lang==='uk');document.querySelector('#lang-en').classList.toggle('active',lang==='en');['pump','generator','valve','vent','cool'].forEach(a=>document.querySelector(`[data-act="${a}"] b`).textContent=T[lang].controls[a]);buildMeters();render()}
function reset(){s={temp:420,pressure:55,power:72,coolant:78,stability:86,pump:false,generator:false,valve:50,vent:false,scram:false};coolCharges=2;fault=null;nextFault=18+Math.random()*7;alive=true;started=performance.now();last=started;restart.classList.add('hidden');log(T[lang].online);render();requestAnimationFrame(loop)}
function log(x){document.querySelector('#log').textContent=x}
function fmt(ms){let sec=ms/1000,m=Math.floor(sec/60),ss=(sec%60).toFixed(1).padStart(4,'0');return `${String(m).padStart(2,'0')}:${ss}`}
function spawnFault(elapsed){let pool=['pump','leak','grid','valve','sensor'];fault=pool[Math.floor(Math.random()*pool.length)];nextFault=elapsed+18+Math.random()*18;log(T[lang].faults[fault]);buzz([90,50,90]);beep(760,.16)}
function clearFault(chance=.42){if(fault&&Math.random()<chance){fault=null;log(lang==='uk'?'Контур відновився. Несправність локалізовано.':'Loop recovered. Fault cleared.');beep(520,.08)}}
function loop(t){if(!alive)return;let dt=Math.min((t-last)/1000,.1);last=t;let elapsed=(t-started)/1000;if(elapsed>nextFault&&!fault)spawnFault(elapsed);let demand=74+8*Math.sin((t-started)/8500)+Math.min(20,elapsed/15);
if(s.scram){s.power-=35*dt;s.temp-=18*dt;s.pressure-=7*dt;s.stability+=5*dt}else{
let pumpEff=s.pump?(fault==='pump'?3.2:9.5):0;
s.power+=(s.generator?8:-2.2)*dt+(s.valve-50)*.045*dt+(demand-s.power)*.045*dt-(fault==='grid'?7*dt:0);
s.temp+=(s.power-64)*.115*dt+(s.generator?2.4:0)*dt-pumpEff*dt;
s.pressure+=(s.temp-410)*.012*dt+(s.valve-50)*.055*dt-(s.vent?9:0)*dt+(fault==='valve'?3.2*dt:0);
s.coolant-=((s.pump?1.15:.13)+(s.vent?.7:0)+(fault==='leak'?2.1:0))*dt;
if(fault==='sensor')s.stability-=4.2*dt;
}
let stress=Math.max(0,s.temp-690)/16+Math.max(0,s.pressure-82)/3+Math.max(0,38-s.power)/4+Math.max(0,22-s.coolant)/2;s.stability+=(2.1-stress)*dt;
for(let k of ['pressure','power','coolant','stability'])s[k]=clamp(s[k],0,k==='power'?120:100);s.temp=clamp(s.temp,0,1100);
if(s.temp>=960||s.pressure>=100||s.stability<=0||s.coolant<=0)die();render();if(alive)requestAnimationFrame(loop)}
function die(){alive=false;let score=performance.now()-started;if(score>best){best=score;localStorage.kirBest=best}status.className='status bad';status.textContent=T[lang].lost;restart.classList.remove('hidden');log(s.temp>=960?T[lang].death[0]:s.pressure>=100?T[lang].death[1]:s.coolant<=0?T[lang].death[2]:T[lang].death[3]);buzz([180,80,180,80,400]);beep(150,.5);render()}
function render(){if(!s)return;let now=alive?performance.now():last;timer.textContent=fmt(now-started);bestEl=document.querySelector('#best');bestEl.textContent=T[lang].best+' '+fmt(best);keys.forEach(k=>{let pct=k==='temp'?s[k]/10:k==='power'?s[k]/1.2:s[k];let bar=document.querySelector('#bar-'+k);if(bar){bar.style.width=clamp(pct,0,100)+'%';bar.classList.toggle('dangerbar',(k==='temp'&&s[k]>720)||(k==='pressure'&&s[k]>82)||(k==='power'&&s[k]<38)||(k==='coolant'&&s[k]<25)||(k==='stability'&&s[k]<35))}let v=document.querySelector('#v-'+k);if(v)v.textContent=Math.round(s[k])+(k==='temp'?'°C':'%')});
let fb=document.querySelector('#faultBox');fb.classList.toggle('hidden',!fault);if(fault)fb.textContent='⚡ '+T[lang].fault+': '+T[lang].faults[fault];
let alarms=[];if(s.temp>720)alarms.push(T[lang].alarms[0]);if(s.pressure>82)alarms.push(T[lang].alarms[1]);if(s.power<38)alarms.push(T[lang].alarms[2]);if(s.coolant<25)alarms.push(T[lang].alarms[3]);if(s.stability<35)alarms.push(T[lang].alarms[4]);document.querySelector('#alarms').innerHTML=alarms.length?alarms.map(a=>`<div class="alarm hot">⚠ ${a}</div>`).join(''):`<div class="alarm">${T[lang].noAlarms}</div>`;
if(alive){let bad=alarms.length>1||alarms.some(a=>s.stability<18),warn=alarms.length>0||fault,st=document.querySelector('#status');st.className='status '+(bad?'bad':warn?'warn':'ok');st.textContent=bad?T[lang].critical:warn?T[lang].warning:T[lang].stable;document.body.classList.toggle('critical',bad)}
document.querySelectorAll('[data-act]').forEach(b=>{let a=b.dataset.act;b.classList.toggle('active',!!s[a]);let sp=b.querySelector('span');if(a==='pump'||a==='generator')sp.textContent=s[a]?T[lang].on:T[lang].off;if(a==='valve')sp.textContent=s.valve+'%';if(a==='vent')sp.textContent=s.vent?T[lang].open:T[lang].closed;if(a==='cool')sp.textContent=coolCharges+' '+T[lang].charges;if(a==='scram')sp.textContent=s.scram?T[lang].fired:T[lang].ready})}
document.querySelector('.controls').addEventListener('click',e=>{let b=e.target.closest('button');if(!b||!alive)return;beep(300,.035);buzz([20]);let a=b.dataset.act;if(a==='pump'||a==='generator'||a==='vent'){s[a]=!s[a];if((fault==='pump'&&a==='pump')||(fault==='grid'&&a==='generator'))clearFault(.55)}if(a==='valve'){s.valve=s.valve>=80?20:s.valve+15;log(T[lang].valveLog+': '+s.valve+'%.');if(fault==='valve')clearFault(.5)}if(a==='cool'&&coolCharges>0){coolCharges--;s.temp-=150;s.pressure-=12;s.coolant=Math.min(100,s.coolant+10);s.stability+=8;log(T[lang].coolLog);if(fault==='leak'||fault==='sensor')clearFault(.35)}if(a==='scram'&&!s.scram){s.scram=true;fault=null;log(T[lang].scramLog);buzz([120,60,240])}render()});
restart.onclick=reset;['uk','en'].forEach(l=>document.querySelector('#lang-'+l).onclick=()=>{lang=l;localStorage.kirLang=l;applyLanguage();log(T[lang].online)});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=004').then(r=>r.update()).catch(()=>{});applyLanguage();reset();